/*
  This is the assets manager
  It allows you to load assets before you start the game
  It also holds onto these assets for later use
*/

class AssetsManager{

  constructor(){
    this._loaded=0;
    this._data={};
  }

  /*
    Calls to this are generated by the engine
    Tells the engine what assets to load before starting the game
  */
  _oncomplete(){}
  _registerImage(path){
    let img=new Image();
    img.src=path;
    let that=this;
    img.onload=function(){
      that._assetRegistered();
    }
    this._data[path]=img;
  }
  _registerAudio(path){
    let that=this;
    let audio=new Audio(path);
    audio.oncanplaythrough=function(){
      that._assetRegistered();
    }
    this._data[path]=audio;
  }
  _assetRegistered(){
    this._loaded++;
    if(this._loaded==Object.keys(this._data).length){
      console.log("Loading complete!");
      this._oncomplete();
    }
  }

  /*
    Returns the percentage progress for loading registered assets
    Returns a floating point value between 0.0 and 1.0
  */
  getProgress(){
    var n=Object.keys(this._data).length;
    if(n==0) return 1.0;
    return this._loaded/n;
  }
  _check(){
    if(!Object.keys(this._data).length){
      console.log("Loading complete!");
      this._oncomplete();
    }
  }

  /*
    Returns the asset associated with the given path
  */
  getAsset(path){
    let img=this._data[`assets/${path}`];
    if(!img) return budgie.error(`Requested asset "${path}" does not exist`);
    return img;
  }
}
