
class AssetsManager{

  constructor(){
    this._loaded=0;
    this._data={};
  }

  /*
    Calls to this are generated by the engine
    Tells the engine what graphics to load before starting the game
  */
  register(path){
    var img=new Image();
    img.src=path;
    let that=this;
    img.onload=function(){
      that._loaded++;
      if(that._loaded==Object.keys(that._data).length){
        console.log("Loading complete!");
      }
    }
    this._data[path]=img;
  }

  /*
    Returns the percentage progress for loading registered assets
    Returns a floating point value between 0.0 and 1.0
  */
  getProgress(){
    var n=Object.keys(this._data).length;
    if(n==0) return 1.0;
    return this._loaded/n;
  }

  /*
    Returns the Image object associated with the given path
  */
  getImage(path){
    return this._data[`assets/${path}`];
  }
}
